# Use uma imagem do Tomcat como base
FROM tomcat:9.0-jre11

# Copie o arquivo WAR do aplicativo para o diretório webapps do Tomcat
COPY ./target/projeto-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/

# Exponha a porta do Tomcat
EXPOSE 8080

# Comando para iniciar o Tomcat
CMD ["catalina.sh", "run"]
